mkdir /home/storage/lung/resultsB/LC_S23_nor
mkdir /home/storage/lung/resultsB/LC_S36_nor
mkdir /home/storage/lung/resultsB/LC_S51_nor
mkdir /home/storage/lung/resultsB/LC_S19_nor
mkdir /home/storage/lung/resultsB/LC_S22_nor
mkdir /home/storage/lung/resultsB/LC_S45_nor
mkdir /home/storage/lung/resultsB/LC_S20_nor
mkdir /home/storage/lung/resultsB/LC_S16_nor
mkdir /home/storage/lung/resultsB/LC_S6_nor
mkdir /home/storage/lung/resultsB/LC_S44_nor
mkdir /home/storage/lung/resultsB/LC_S33_nor
mkdir /home/storage/lung/resultsB/LC_S27_nor
mkdir /home/storage/lung/resultsB/LC_S37_nor
mkdir /home/storage/lung/resultsB/LC_S24_nor
mkdir /home/storage/lung/resultsB/LC_S38_nor
mkdir /home/storage/lung/resultsB/LC_S48_nor
mkdir /home/storage/lung/resultsB/LC_S28_nor
mkdir /home/storage/lung/resultsB/LC_S32_nor
mkdir /home/storage/lung/resultsB/LC_S39_nor
mkdir /home/storage/lung/resultsB/LC_S14_nor
mkdir /home/storage/lung/resultsB/LC_S41_nor
mkdir /home/storage/lung/resultsB/LC_S8_nor
mkdir /home/storage/lung/resultsB/LC_S47_nor
mkdir /home/storage/lung/resultsB/LC_S26_nor
mkdir /home/storage/lung/resultsB/LC_S46_nor
mkdir /home/storage/lung/resultsB/LC_S31_nor
mkdir /home/storage/lung/resultsB/LC_S52_nor
mkdir /home/storage/lung/resultsB/LC_S34_nor
mkdir /home/storage/lung/resultsB/LC_S13_nor
mkdir /home/storage/lung/resultsB/LC_S50_nor
mkdir /home/storage/lung/resultsB/LC_S35_nor
mkdir /home/storage/lung/resultsB/LC_S40_nor
mkdir /home/storage/lung/resultsB/LC_S17_nor
mkdir /home/storage/lung/resultsB/LC_S43_nor
mkdir /home/storage/lung/resultsB/LC_S10_nor
mkdir /home/storage/lung/resultsB/LC_S15_nor
mkdir /home/storage/lung/resultsB/LC_S25_nor
mkdir /home/storage/lung/resultsB/LC_S9_nor
mkdir /home/storage/lung/resultsB/LC_S18_nor
mkdir /home/storage/lung/resultsB/LC_S21_nor
mkdir /home/storage/lung/resultsB/LC_S49_nor
mkdir /home/storage/lung/resultsB/LC_S42_nor
mkdir /home/storage/lung/resultsB/LC_S30_nor
mkdir /home/storage/lung/resultsB/LC_S29_nor
mkdir /home/storage/lung/resultsB/LC_S11_nor
